Develop
ChiaJung1031/taipei-day-trip-website pull request #8
Opened 2021-05-13 14:40 UTC by ChiaJung1031

李佳蓉
http://3.114.48.184:3000/
http://3.114.48.184:3000/attraction/2

2021-05-13 16:29 UTC, cwpeng requested changes
幾件事情請修正：
1. 密碼請使用密碼輸入框，不要明碼顯示。
2. 以下是 1920px、800px、和 414px 的版面狀況，都需要調整好哦 ( 使用固定寬度置中即可 )
![3 114 48 184_3000_](https://user-images.githubusercontent.com/6104683/118156033-74cbeb00-b44b-11eb-9b2a-421e2be64a97.png)
![3 114 48 184_3000_ (1)](https://user-images.githubusercontent.com/6104683/118156043-77c6db80-b44b-11eb-8cea-e620e179b0af.png)
![3 114 48 184_3000_ (2)](https://user-images.githubusercontent.com/6104683/118156050-79909f00-b44b-11eb-94ef-694f301fc098.png)

2021-05-14 02:09 UTC, ChiaJung1031 commented
李佳蓉
http://3.114.48.184:3000/
http://3.114.48.184:3000/attraction/2

已將登入畫面固定大小~並且將明碼修改掉~

2021-05-14 04:12 UTC, cwpeng commented
網站連不上哦，恢復正常了再和我說 ~

2021-05-14 05:54 UTC, ChiaJung1031 commented
我有重新啟動一次了! 再麻煩老師查看一下~

2021-05-14 07:08 UTC, cwpeng approved these changes
好哦，這樣就可以了 :)

不過你的登入表單中的密碼還是沒有處理好，但我相信你可以自己處理好之後再一起給我就好 ~

2021-05-14 07:15 UTC, ChiaJung1031 commented
![image](https://user-images.githubusercontent.com/76677263/118235260-18a6ac80-b4c7-11eb-9bfd-78f3cbbe5cf3.png)
咦~是指註冊畫面的密碼部分也不能用明碼嗎?! 我只有改登入頁面~我以為註冊頁面可以讓使用者看到他輸入的!

2021-05-14 07:19 UTC, cwpeng commented
哦哦，是註冊的，對哦，基本都不會是明碼，你可以多去試試看常見的網站。頂多是給一個按鈕讓他有機會是明碼，但都是預設為非明碼的 ~

2021-05-14 07:37 UTC, ChiaJung1031 commented
好的~了解~我已修改好! 下回會一併繳交~謝謝老師~

2021-05-14 07:38 UTC, merged